export const FEATURE_PRESETS: Record<string, string[]> = {
  "Frontend & UI": [
    "Landing Page",
    "Responsive Design",
    "Admin Dashboard",
    "PWA",
    "Mobile Responsive",
  ],
  "Auth": [
    "Login",
    "Signup",
    "Authentication",
    "User Roles",
    "OTP Login",
    "Social Login",
  ],
  "Commerce": [
    "Product Management",
    "Categories",
    "Inventory",
    "Orders",
    "Cart",
    "Wishlist",
    "Coupons",
    "Multi Vendor",
  ],
  "Payments": [
    "Payment Gateway",
    "Razorpay",
    "Stripe",
    "Cash on Delivery",
  ],
  "Discovery": ["Search", "Filters", "Reviews"],
  "Content": ["CMS", "Blog", "SEO", "Contact Form"],
  "Analytics": ["Analytics", "Dashboard", "Reports"],
  "Comms": [
    "WhatsApp Integration",
    "Email Notifications",
    "SMS",
    "Push Notifications",
    "Chat Support",
  ],
  "Integrations": [
    "API Integration",
    "Google Maps",
    "Multi Language",
  ],
  "Deployment": [
    "Hosting Setup",
    "Domain Setup",
    "SSL",
    "CDN",
    "Performance Optimization",
    "Security",
    "Backup",
    "Deployment",
    "Documentation",
    "Training",
  ],
};

export const MAINTENANCE_PRESETS = [
  "Bug Fixes",
  "Security Updates",
  "Content Changes",
  "Product Uploads",
  "Image Changes",
  "Banner Updates",
  "Performance Optimization",
  "Database Backup",
  "SSL Monitoring",
  "Server Monitoring",
  "Technical Support",
  "Monthly Reports",
  "Uptime Monitoring",
  "SEO Fixes",
  "Plugin Updates",
  "Minor Design Changes",
  "Feature Requests",
  "Emergency Support",
];